LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'demo'
OUTPUT_DIR: 'experiments/'
NUM_WORKERS: 0
MODEL_CONFIG: 'configs/yamls/model_base_3dpw.yaml'
FLIP_EVAL: True

TRAIN:
  STAGE: 'stage2'
  POSE_CHECKPOINT: ''
  CHECKPOINT: 'checkpoints/pmce_plus_3dpw.pth.tar'

MODEL:
  BACKBONE: 'vit'

DATASET:
  SEQLEN: 81
